server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

spring:
  application:
    name: RD-Name
  datasource:
    url: jdbc:postgresql://localhost:5432/social_prod
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: reverse_schema

flyway:
  enabled: false

logging:
  level:
    com.orange: INFO
  file: logs/development-logging.log

eureka:
  instance: # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/