server:
  port: 5555

spring:
  application:
    name: RD-Name
  datasource:
    url: jdbc:postgresql://localhost:5432/social
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: reverse_schema

flyway:
  enabled: false

logging:
  level:
    com.orange: DEBUG
  file: logs/development-logging.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
